### ISSUE TITLE
Allow committee to update calendars

### ISSUE THREAD

**Issue by mileswatson** [christsjcr/website#159]
Allow the website calendars (e.g. freshers events, termcard) to be edited by other JCR members.

One potential solution is:
- Creating different calendars for freshers, termcard etc. in the webmaster Google Calendar account
- Changing current webcal links to google webcal links
- Adding support for fetching and parsing the webcal events on the website, so they can be displayed nicely. [This library](https://www.npmjs.com/package/node-ical) may come in useful.

**Comment by rachleona** [comment]
Closed by #211
